/* Peters favoritter og derez til indstillingen "Use Peter's picks". Genereret af scripts/lib/peter-picks.js;
 * redigér ikke i hånden. */
window.gridPeterPicks = {
 "favorites": [
  "_Flexi, martin + geiss - painterly rogue wave strike (color emboss mix)",
  "_Mig_COLORFUL9",
  "$$$ Royal - Mashup (217)",
  "$$$ Royal - Mashup (253)",
  "298",
  "420",
  "A Ultimate AdamFX 2 Martin - disco mix 6 (UFO RMX)Inside the ship (thereShooting)Flexi,Fishbrain,Hexocollie 5",
  "amandio c - feeling well 3 more menace ruine",
  "amandio c - iterative - orbits 2 i am ingrate",
  "amandio c - iterative - orbits 2 i am ingrate tear the life from you, you already dead",
  "Bdrv EoS - blueberry jam",
  "beta106i - Airhandler (Last Breath - Eden)",
  "CantStop AdamFX 2 Stahlregen & Bmelgren + EoS + Geiss + Krash + Rocke + Rovastar - Glowstick Heart (MashUp 7)",
  "cope - soar (v2.0)",
  "Cope - The Neverending Explosion of Red Liquid Fire",
  "Eo.S. + Phat - cubetrace - v2",
  "EoS - cubetrace demon_Phat_edit_2",
  "EoS - glowsticks v2 04 music minimal - ghosts nz+3",
  "EoS - heater core B",
  "EoS - heater core C_Phat's_class_mix",
  "EoS - magnetosphere 04",
  "EoS - magnetosphere 06 - birthegg",
  "EoS - magnetosphere 11 - polarsphere-warp",
  "EoS_Phat technicolor E breather B",
  "fed - slowfast 1.1",
  "Flexi - braggadocio",
  "Flexi - fractal tree",
  "Flexi - oldschool tree",
  "Flexi - the early bird",
  "Flexi + Martin - astral projection",
  "Flexi, Rovastar + Geiss - Fractopia vs bas relief",
  "Goody - Clouded Reason - revisited",
  "Goody - Ego Decontructor",
  "Halfbreak + Flexi - Rainbow Tree (Turn Bigs Mix)",
  "Idiot - Marphets Surreal Dream (Hypnotic Spiral Mix)",
  "LuxXx - Hurty Eyes II",
  "LuxXx - Melt Ur Face i",
  "LuxXx - RainbowTwitcher Charge(d)",
  "LuxXx - Spiral Machina (langoliers sherrell mix)",
  "malalol + Flexi mad peyote on lousy socks",
  "Martin - acid wiring",
  "martin - the forge of Isengard",
  "Mstress - Acoustic Nerve Impulses",
  "ORB - Acid Cycle Gas Giant",
  "ORB - Fire and Fumes 2",
  "ORB - Solar Sail",
  "Phat and EoS _ shapes are cool demon",
  "Phat_Zylot_EoS Trippy_rotation_v2_sector_mix",
  "Rarian Rakista - Pyraid Power",
  "rce-ordinary + flexi - far away distance (custom beat detection + bipolar colour ghost mix)",
  "Rovastar - eclectic interface (despair mix)",
  "Rovastar & Loadus - FractalDrop (Active Sparks Mix)",
  "Rovastar & Malte - Circle Of Deeper Meaning",
  "Rovastar + Geiss - Hyperkaleidoscope Glow 2 motion blur (Jelly)",
  "Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)",
  "Rovastar + Loadus + Geiss - Tone-mapped FractalDrop 7c",
  "ShadowHarlequin - Fitting Butterfly - v4 - [Loadus & Geiss - FractalDrop 22] v2v2v2v2newcolorsv2v2-22v2-NEWv222v2",
  "shifter - feathers (angel wings)_phat_Updated_Ugly_colors_remix",
  "shifter - glassworms flare",
  "shifter - liquid circuitry",
  "shifter - liquid circuitry - model without work",
  "shifter - mandala",
  "shifter - plasmic fact - witholding, with-a holding, widdaholting - voyeurulant roam3 enormous hog pig",
  "shifter - urchin kali echos",
  "shifter + Flexi - liquid circuitry from the lesser evil hive",
  "shifter + Flexi - liquid circuitry from the waxen hive nz+",
  "Shifter-yak(yetanotherkaleidoscope)00",
  "Shifter-yak(yetanotherkaleidoscope)02",
  "Stahlregen - Eckshack's Eyeball (floater mix) - qlean luchre nz+",
  "stahlregen - hypnotron v 0-5 - the unfathomable force and terror of the dormant overmind",
  "Stahlregen & Geiss + Pithlit + PieturP - Dark Ritual (Etheral)_1",
  "suksma - biotoxins on strings - papa smurf kingpin + flx per vtx equ(1)",
  "suksma - biotoxins on strings - quantizied bacteria line alien bioluminescent intestine + flx per vtx equ",
  "suksma - coal drapes - mrt fsh gordo dog crap in my bed cuz i sleep wid my shoes on",
  "suksma - coal drapes - mrt fsh smelter nz+",
  "suksma - diploautomatic autoimmunity vs passivematic aggpressive",
  "suksma - fiShbRaiN - witchcraft (phugly shame on remix) - darning kneedless - ap3 exro - horsebasket radishbubble",
  "suksma - fiShbRaiN - witchcraft (phugly shame on remix) - darning kneedless - ap3 exro - intimidation through passivity",
  "suksma - gasfunk lipidmalarial causticidiary flounderdouse",
  "suksma - jerry kludging the dimswitch",
  "suksma - moonthy memeses (non-reproductive thought blood)",
  "suksma - sordid punk melt refrain",
  "suksma - tetraxectsual aeliaen kkuhltz --- Isosceles edit05",
  "suksma - yin - 395 - Artificial Inspiration (brainstorming - outward) + martin + flexi - elephant mating",
  "yin - 315 - Ocean of Light (yo im peakin yo EoS-Phat)",
  "yin - 390 - Artificial Inspiration",
  "Zylot - Crosshair Dimension (Light of Ages)",
  "Zylot & Idiot - Face zzz9"
 ],
 "derez": [
  "141",
  "211",
  "AdamFx 2 Geiss, Zylot and Flexi - Reaction Diffusion 3 (Overload Mix 2) EATIT4 (BCCNJ4)",
  "Aderrasi - Hard Drink (Half-Infinitea)",
  "Aderrasi - Songflower (Hybrid Plant)",
  "afunction knegatson windpissinglistening",
  "akish - placard - you were always so hard to find",
  "amandio c - knot - dead hogs",
  "Bdrv Aderrasi - Accelerator (Orbital Migraine) BDRV et AL rmx8 - loavthe is a con-tact spwhore-T(honTh",
  "beta106i - Airhandler (Last Breath - Crab Handler)",
  "cleave and cleave to thine w thankee sai for more trippy ass shit hail",
  "cope + flexi - colorful marble (ghost mix) - rand wave 3",
  "cope + flexi - colorful marble (ghost mix) - rand wave 3 nz+",
  "dark cloud",
  "EoS - ether posession_phat_edit_v3",
  "EoS - Phat - randombox - mantra 5 response lullquestent vlasphume foam blocks candy taste nz+",
  "EVET - Zorn Church",
  "fat cancer arched ass nun",
  "fed + Flexi - plasma pong 1-4",
  "fewgasm",
  "fewgasm drugged by kenyans",
  "fewgasm drugged by kenyans nz+ nandgasm vs topological transform dynamics",
  "fiShbRaiN - witchcraft (metropolish remix) - test - tillex  - bob boyce' 'the cell', pulstar, singh grooves",
  "fiShbRaiN - witchcraft (metropolish remix) - test - tillex  - mbor irritense foul week eun",
  "Flexi - fractal descent gnesse pitstash io",
  "Flexi + Geiss - I dont know how to call this mashup",
  "Geiss + Stahlregen - Reaction Diffusion 3 [Rippling Islands] - rage crotch",
  "Goody - Lightning - Vegas Dreamer remix (PS2-0) - mix",
  "goody + flexi - emotive dissonance - integral anomaly mix",
  "gwadeloag - phusillyty roams",
  "Hakan + Flexi - Dark Tiles (shadow influence + injection theory)",
  "Hexcollie, Flexi n Suksma - Yep, LSD in my morning coffee",
  "infinitely symbolic - infinitely finite (zaemngouhlaerapethaee)",
  "NiGHtHawK - Eye of Gawd_Phat_Spiral_edit_v2",
  "Pithlit - Golden Rays",
  "propre possess i only want lindsay",
  "Rovastar - Harlequin's Fractal Encounter - more blood oaths nz",
  "Rovastar & Loadus + Zylot - FractalDrop (Spark Machine v2.0)",
  "Rovastar + Flexi + Loadus + Geiss - Tone-mapped FractalDrop 4 [moebius edit]",
  "Rovastar + Loadus + Geiss - Tone-mapped FractalDrop 7b",
  "Serge circles001",
  "ShadowHarlequin - Fitting Butterfly - v7 - [Loadus & Geiss - FractalDrop 22] neon starscapev2",
  "shifter - phasm wraith (fps+ mix) neck problem solution (tense for hours) antitheses",
  "Shifter - Phat - Gastly - Flexi - Krash - 120294848617(71)",
  "shifter - plasmic fact - witholding, with-a holding, widdaholting - 3-lay",
  "shifter - robotopia v2 molding chaos all four waves mange vs lice vs mites",
  "shifter - swarm",
  "signed 'nuph phoaqing death warrants i don't have time for time if anything, i'm mad at the developers, fnord",
  "Stahlregen - Dots (Pixels - reactive blur)",
  "Stahlregen & Boz + EoS + Geiss + Phat + Rovastar + Zylot - Machine Code (Relief Block Mix) (Jelly)",
  "Stahlregen & Flexi + Geiss + Martin + Rovastar + Telek - DiskWasher (Gentle RMX 2)_3",
  "suksma - dotes hostile undertake - antiborg - lifeless",
  "suksma - dotes hostile undertake - can't even remember her blood mist eminant",
  "suksma - dotes hostile undertake - can't even remember her blood mist eminant roam3",
  "suksma - dotes hostile undertake - can't even remember her roam",
  "suksma - dotes hostile undertake - j4+ - flacc",
  "suksma - dotes hostile undertake - more raisins",
  "suksma - inverting your soul until you are quivering spirit meat",
  "suksma - jim class --- Isosceles edit",
  "suksma - neck problems",
  "suksma - no, i don't know what the hell it is, but i'm eating it for mind lunch2",
  "suksma - penattrition - geiss crossfire shaders nz+ gssm2",
  "suksma - rapture garden make out pumps",
  "suksma - satanic teleprompter - sulb",
  "suksma - sick star bloat --- Isosceles edit19",
  "suksma - staves",
  "suksma - stinkin lougs on fluxi's schzest - necro nz+",
  "suksma - subharmonic overtone placebo timbre throttle",
  "suksma - taking turns with sharae and charise - bristle grizzle",
  "suksma + rovastar eos phat rediJedi adamfx - the future of oreos",
  "Syst3mFailur - satanic ring V2 nz+ --- Isosceles edit3",
  "various artists - 120093435564(270)",
  "Waltra - Blurry Balls",
  "Waltra - Burning Spiral",
  "Waltra - Veil Fire",
  "yin - 190 - Temporal fluctuations",
  "yin - 191 - Temporal singularities --- Isosceles edit",
  "yin - 191 - Temporal singularities aaa",
  "yin - 314 - Ocean of Light (ascending nadi mix)",
  "yin - 392 - Artificial Inspiration - utterly destroy the whole point for nihilistic fun",
  "Zylot - Crystal Ball (Magical Reaction Mix)",
  "Zylot - new work",
  "Zylot - Star Ornament"
 ]
};
